### ISSUE TITLE
Its not works in /etc/rc.local

### ISSUE THREAD

**Issue by ARogovsky** [kryptco/kr#103]
Hi!

I was tested kr from cli - it works.
But I want implement it to rc.local for batch connect when machine is started.
And kr is not works in rc.local.

**Comment by kcking** [comment]
Sorry not sure I understand the use case exactly. Do you have some `ssh` commands that run in rc.local that you want to run using the Kryptonite `ssh` key?

**Comment by ARogovsky** [comment]
Yes, I want get message in my phone app every time when my laptop is turn on. Something like MFA.

**Comment by kcking** [comment]
Sorry for the late response. Since we removed `systemd` support, there may now be a hacky way to do this -- assuming rc.local is run by root. Just add the same SSH configuration lines that Kryptonite adds to `~root/.ssh/config`. Next log in as root, `unset SUDO_USER` so it doesn't fall back to your normal user, and `kr pair`. Then a `ssh me.krypt.co` command in rc.local should invoke Kryptonite.
