### ISSUE TITLE
Cannot determine host with mosh

### ISSUE THREAD

**Issue by LukeXuan** [kryptco/kr#111]
When I'm establishing connection with `mosh`, the Android app notifies with `unknownhost`, but it works correctly with `ssh`. Is there any possibility to work correctly with `mosh`?

**Comment by kcking** [comment]
Since `mosh` runs over UDP, our current architecture isn't able to locally capture the handshake packets from the remote host (which is the purpose of our` ProxyCommand` configuration option).

There is some good background on related issues users have had with `mosh` here: https://github.com/mobile-shell/mosh/issues/285

What features of `mosh` are desirable to you over `ssh`?

**Comment by LukeXuan** [comment]
`mosh` provides much better experience when I have poor Internet conditions. I see it may be hard to support.

**Comment by stigtsp** [comment]
Hey I've looked into this a bit and there seems to be a workaround in mosh that sets the correct hostname. 

mosh --experimental-remote-ip=remote user@host

An added benefit is that the "Kryptonite ▶ Phone approval..." messages also end up in the current terminal.

**Comment by LukeXuan** [comment]
@stigtsp wow that's mostly perfect, at least enough for me!

**Comment by kcking** [comment]
Great, glad you found a workaround @stigtsp ! I am going to close this issue for now, please let us know if any other mosh-related issues crop up

**Comment by pugthelouie** [comment]
When trying to use `mosh` with my server, I have to use the `--ssh "ssh -p 2433"` `mosh` parameter to login. This workaround seems to conflict with this; as my server no longer accepts any incoming connections. Why could this be? Switching back to `ssh` fixes this problem.
