### ISSUE TITLE
Request fails even though I get a notification on the phone that says it is allowed

### ISSUE THREAD

**Issue by vikeri** [kryptco/kr#127]
Kryptonite ▶ Request timed out. Make sure your phone and workstation are paired and connected to the internet and the Kryptonite app is running.

macOS
Android 7.1.2

**Comment by kcking** [comment]
Hi Viktor, thanks for reporting.

Can you check the `system.log` tab of `Console.app` to see if `krd` is printing any errors?

**Comment by vikeri** [comment]
```
krd[82427]: 09:41:50.155 ERROR ▶ CoreBluetooth: CBAdvertisingDriver.m:341 Error advertising: Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo={NSLocalizedDescription=Unknown error.}
```

```
 krd[1118]: 16:39:11.984 ERROR ▶ Request timed out
 krd[1118]: 2017/06/19 16:39:12 agent 13: Request timed out
 krd[1118]: 16:39:14.207 ERROR ▶ evicting request 6SIZyUUN6Xeer...
```

**Comment by kcking** [comment]
Is this happening consistently for you? Also, could you please provide the output of `kr debugaws`?

**Comment by vikeri** [comment]
Yes it happens to me always after I haven't used it for a while. If I have the phone screen unlocked it does not happen. And usually it works the second time I try it. I have the WiFi in power save mode on my Android (not connected all the time unless I am charging it).

```
$ kr debugaws
Create SQS Queue took 628ms
Send SQS Message took 139ms
Receive SQS Message took 271ms
AWS connectivity check succeeded.
```

**Comment by vikeri** [comment]
Have to abandon kryptonite until this is resolved

**Comment by kcking** [comment]
Sorry about that Viktor. I'm guessing it is a problem related to WiFi power save mode. Are you referring to battery saver mode? I don't see an explicit WiFi low power mode on my Pixel. Also some more details might be useful in further debugging this:

What type of android phone are you using? Does this happen for only auto-approved requests or manually approved requests as well? About how long is Kryptonite inactive for before you try the failed request?

Thanks!

**Comment by vikeri** [comment]
Yeah exactly, the WiFi power save mode, not battery saver mode. I'm using an Android Nexus 5X, it happens for both auto-approved and manually approved requests. It's inactive for a couple of hours.

**Comment by oskapt** [comment]
I'm in this situation as well. Starting a few weeks ago I noticed that using Kryptonite with my iPhone caused service disruptions with other Bluetooth devices (Magic Trackpad, Keyboard). It got to where my other devices would disconnect/reconnect multiple times an hour. Sometimes Kryptonite would also stop working, and I'd see the Bluetooth icon on the phone flashing showing connection/disconnection repeatedly. I could get it to work again by some combination of:

1. `kr restart`
2. Restart the app on my phone
3. Bounce Bluetooth on my Mac and/or on my phone

Starting a couple of weeks ago, Krypt appears to have stopped using Bluetooth altogether. I no longer see a connection from my Mac to my iPhone in the Bluetooth preference pane. I assumed that it had fallen back to SQS. Sometimes it would still time out - my phone would approve the request, but my Mac would time out waiting for it. I could often fix this by some combination of #1 and #2 from above.

Today it just doesn't work at all. It times out 100% of the time. The only errors reported in `system.log` are timeouts or me using `^C` because I'm tired of waiting for it:

```
Sep 29 13:27:35 ferdinand krd[62715]: 13:27:35.869 NOTICE ▶ CoreBluetooth: CBDriver.m:118 Writing data to characteristic
Sep 29 13:27:37 ferdinand krd[62715]: 13:27:37.943 NOTICE ▶ pushing alert for request 1tC1Yx59XJlTRTtTrYtoEZ
Sep 29 13:27:59 ferdinand krd[62715]: 13:27:59.535 NOTICE ▶ CoreBluetooth: CBDriver.m:118 Writing data to characteristic
Sep 29 13:28:01 ferdinand krd[62715]: 13:28:01.607 NOTICE ▶ pushing alert for request 4wyhUBvfhEGgxCSmpkgLqN
Sep 29 13:28:05 ferdinand krd[62715]: 13:28:05.888 ERROR ▶ evicting request 1tC1Yx59XJlTRTtTrYtoEZ
Sep 29 13:28:05 ferdinand krd[62715]: 13:28:05.888 ERROR ▶ no signature response
Sep 29 13:28:05 ferdinand krd[62715]: 2017/09/29 13:28:05 agent 13: no signature response
Sep 29 13:28:29 ferdinand krd[62715]: 13:28:29.535 ERROR ▶ Request timed out
Sep 29 13:28:29 ferdinand krd[62715]: 2017/09/29 13:28:29 agent 13: Request timed out
Sep 29 13:28:31 ferdinand krd[62715]: 13:28:31.767 ERROR ▶ evicting request 4wyhUBvfhEGgxCSmpkgLqN
Sep 29 13:28:43 ferdinand krd[62715]: 13:28:43.475 NOTICE ▶ CoreBluetooth: CBAdvertisingDriver.m:195 removeService: EBD2A609-BF83-3887-6678-9A84B629CA8F
Sep 29 13:28:43 ferdinand krd[62715]: 13:28:43.475 NOTICE ▶ CoreBluetooth: CBAdvertisingDriver.m:255 stopAdvertising
Sep 29 13:28:43 ferdinand krd[62715]: 13:28:43.475 NOTICE ▶ CoreBluetooth: removed service ebd2a609-bf83-3887-6678-9a84b629ca8f
Sep 29 13:28:43 ferdinand krd[62715]: 13:28:43.476 NOTICE ▶ stopping with signal terminated
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.251 NOTICE ▶ krd launched and listening on UNIX socket
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.253 NOTICE ▶ CoreBluetooth: CBDriver.m:82 Adding service [CBUUID EBD2A609-BF83-3887-6678-9A84B629CA8F] with characteristics {
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.256 NOTICE ▶ CoreBluetooth: CBAdvertisingDriver.m:114 Queued service <CBMutableService: 0x5500240 Primary = YES, UUID = [CBUUID EBD2A609-BF83-3887-6678-9A84B629CA8F], Included Services = (null), Characteristics = (
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.256 NOTICE ▶ CoreBluetooth: added service ebd2a609-bf83-3887-6678-9a84b629ca8f
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.256 NOTICE ▶ CoreBluetooth: CBAdvertisingDriver.m:306 CBPeripheralManagerStatePoweredOn
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.257 NOTICE ▶ CoreBluetooth: CBAdvertisingDriver.m:246 startAdvertising (
Sep 29 13:30:12 ferdinand krd[64476]: 13:30:12.257 NOTICE ▶ CoreBluetooth: CBScanningDriver.m:268 CBCentralManagerStateOn
Sep 29 13:30:24 ferdinand krd[64476]: 13:30:24.571 NOTICE ▶ CoreBluetooth: CBDriver.m:118 Writing data to characteristic
Sep 29 13:30:26 ferdinand krd[64476]: 13:30:26.645 NOTICE ▶ pushing alert for request 43gRlnZ4SZnq53N9PDKSZD
Sep 29 13:30:54 ferdinand krd[64476]: 13:30:54.644 ERROR ▶ Request timed out
Sep 29 13:30:54 ferdinand krd[64476]: 13:30:54.738 ERROR ▶ evicting request 43gRlnZ4SZnq53N9PDKSZD
Sep 29 13:30:54 ferdinand krd[64476]: 2017/09/29 13:30:54 agent 13: Request timed out
Sep 29 13:31:14 ferdinand krd[64476]: 13:31:14.590 NOTICE ▶ CoreBluetooth: CBDriver.m:118 Writing data to characteristic
Sep 29 13:31:16 ferdinand krd[64476]: 13:31:16.659 NOTICE ▶ pushing alert for request 4evD4CGs9S2HBupPxjy4t0
Sep 29 13:31:44 ferdinand krd[64476]: 13:31:44.663 ERROR ▶ Request timed out
Sep 29 13:31:44 ferdinand krd[64476]: 2017/09/29 13:31:44 agent 13: Request timed out
Sep 29 13:31:46 ferdinand krd[64476]: 13:31:46.702 ERROR ▶ evicting request 4evD4CGs9S2HBupPxjy4t0
```

I love Kryptonite. I've shown it to everyone I know, but it has crossed a line from useful to hindrance. If you have any suggestions for making it more reliable, I'm all ears...but until then, I unfortunately have to follow @vikeri and disentangle myself from using it everywhere.

**Comment by agrinman** [comment]
@oskapt I'm sorry you're having these troubles, we definitely want to help you fix them ASAP. What version of macOS / iPhone are you on? We are recently aware of this bluetooth interruption issue and are working on a redesign of how bluetooth works to permanently fix this -- however since updating to both iOS 11 & macOS 10.13 (High Sierra) the bluetooth issue for me seems to have gone away...maybe this is a viable option for you to upgrade, or if it's still the case it is important for us to know. Please bare with us as it's our top priority for Kryptonite to never get in the way of your workflow.

**Comment by kcking** [comment]
Our bluetooth rewrite has resolved these stability issues, please upgrade to kr and Kryptonite 2.3.0+ and let us know if you still have any issues!
