### ISSUE TITLE
If `kr-pkcs11.so` is not found, `ssh me.krypt.co` still mistakenly tells the user that they have been authenticated.

### ISSUE THREAD

**Issue by tylerhou** [kryptco/kr#171]
### Reproduction

- Edit ~/.ssh/config to point to a wrong path for `kr-pkcs11.so`.
- `ssh me.krypt.co`

[
<img width="906" alt="screen shot 2017-12-05 at 3 46 00 pm" src="https://user-images.githubusercontent.com/5315734/33637317-1a86b692-d9d5-11e7-9ff1-5f5a1b507ee4.png">
](url)

**Comment by kcking** [comment]
Thanks for reporting! The way we detect whether you are using a Kryptonite key is actually just a heuristic since we don’t collect or store public keys (we only use the key type since most users have a 2048-bit rsa key). In this way, people with large RSA, ed or ecdsa keys will be false positives. Please let us know if you run into any other issues!
