### ISSUE TITLE
RPM - krd is started as root and `kr pair` fails

### ISSUE THREAD

**Issue by gtirloni** [kryptco/kr#175]
Following the install instructions on Fedora using the RPM package, krd is started automatically as root. Further running `kr pair` fails complaining that the kr daemon is not accessible. 

The workaround is to kill the root-owned krd process and run `kr restart` as a standard user.

I see the RPM postinstall scripts tries to work with a systemd unit but I can't find it anywhere in my system (Fedora 27) or in the package itself.

```
$ rpm -qp kr-2.3.1-1.el7.centos.x86_64.rpm --scripts
postinstall scriptlet (using /bin/sh):
# remove potentially existing systemd service for current user
ls /etc/systemd/system/default.target.wants/kr.service 2>/dev/null 1>/dev/null && (sudo systemctl disable kr 1>/dev/null 2>/dev/null; sudo systemctl stop kr 1>/dev/null 2>/dev/null) || true
sudo rm /etc/systemd/system/default.target.wants/kr.service 2>/dev/null 1>/dev/null || true
sudo su ${SUDO_USER:-$USER} <<EOF
mkdir -m 700 -p ~/.ssh
touch ~/.ssh/config
chmod 600 ~/.ssh/config
# delete old kr ssh config
kr restart 1>/dev/null 2>/dev/null
EOF
echo Krypton is now installed! Type \"kr pair\" to pair with the Kryptonite app.
```

```
$ sudo ls /etc/systemd/system/default.target.wants/kr.service
ls: cannot access '/etc/systemd/system/default.target.wants/kr.service': No such file or directory
```

This might be a separate issue (will krd started next time the system is rebooted?)

**Comment by kcking** [comment]
Thank you for reporting. We used to use systemd, but no longer use it to keep krd running. Those lines are intended to make sure any remaining systemd config from an older version are not present.

We have updated our RPM package to 2.3.1-2 (it may be cached at 2.3.1-1 for a few more minutes). The install script now just kills any running `krd` process so that the next invocation of `kr` or `ssh` will automatically start it as the correct user. Let us know if you have any other issues!
