### ISSUE TITLE
Can't use the kryptonite ed25519 public key with AWS

### ISSUE THREAD

**Issue by marcopaga** [kryptco/kr#94]
I tried to use `kr aws` to use my public key with the Amazon Web Services. After clicking on Import, pasting the key and clicking on Import I get this error: 
"*Error importing Key Pair*
Key is not in valid OpenSSH public key format"

**Comment by kcking** [comment]
Are you using an ed25519 key? Unfortunately AWS does not support these yet, we will add a better error message. I have asked them to add support but I don't expect a quick turnaround.

Once we support multiple keys, you will be able to use an ed25519 key for most things and an RSA key for incompatible services like AWS.

**Comment by marcopaga** [comment]
Yes, I'm using the ssh-ed25519 key. I wasn't aware that this is an expected behavior. Thank you for clarifying.

**Comment by FernandoMiguel** [comment]
Are you guys referring to AWS AMI Linux?
It does support ed25519

**Comment by agrinman** [comment]
@kcking is referring to the import public key utility in the AWS console (EC2 Dashboard) that won't take ed25519 public keys. See here:
<img width="1528" alt="screen shot 2017-05-05 at 6 31 17 pm" src="https://cloud.githubusercontent.com/assets/356333/25766527/1054d4d6-31c1-11e7-9d4d-69123eadc7cc.png">

**Comment by marcopaga** [comment]
The problem ist that `kr aws` will send you to the import site which can't handle the key that is placed in the clipboard by kr. That is imho very confusing.

**Comment by wangkesen** [comment]
How so? The majority of users who use AWS would know since its specifically stated that AWS doesn't support ECDSA keys. So it's not like your suddenly expecting KR to suddenly offer a way to use ECDSA keys where they were not functional previously with AWS right?

Either way yes clarification is needed that specifies you're exporting RSA keys and that DSA are not supported, but I don't see how it's confusing, that's something you should have been aware of as an AWS user beforehand I feel.

**Comment by marcopaga** [comment]
@wangkesen `kr aws` sends me to a site that can't handle the key. Yes this is not a great UX. Doesn't matter how many people know it.

**Comment by kcking** [comment]
Yes we agree this is a UX bug, let's keep the issue open :)
